# Generated by Django 4.0.1 on 2022-01-10 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(null=True, upload_to='CategoryImages')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('gst_id', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('Android', 'Android'), ('ios', 'ios'), ('Symbian', 'Symbian'), ('Windows', 'Windows')], max_length=40)),
                ('price', models.BigIntegerField()),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(default='', null=True)),
                ('in_stock', models.IntegerField()),
                ('info', models.TextField(null=True)),
                ('image1', models.ImageField(upload_to='MobileImages')),
                ('image2', models.ImageField(upload_to='MobileImages')),
                ('image3', models.ImageField(upload_to='MobileImages')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seller')),
            ],
            options={
                'verbose_name_plural': 'Category Mobiles',
            },
        ),
        migrations.CreateModel(
            name='HomeDecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('Bedsheets', 'Bedsheets'), ('Clocks', 'Clocks'), ('Lights', 'Lights'), ('Paintings & Posters', 'Paintings & Posters')], max_length=40)),
                ('price', models.BigIntegerField()),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(default='', null=True)),
                ('in_stock', models.IntegerField()),
                ('info', models.TextField(null=True)),
                ('image1', models.ImageField(upload_to='HomeDecorImages')),
                ('image2', models.ImageField(upload_to='HomeDecorImages')),
                ('image3', models.ImageField(upload_to='HomeDecorImages')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seller')),
            ],
            options={
                'verbose_name_plural': 'Category Home Decor',
            },
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Casual Shoes', 'Casual Shoes'), ('Formal Shoes', 'Formal Shoes'), ('Jeans', 'Jeans'), ('Trousers', 'Trousers')], max_length=40)),
                ('price', models.BigIntegerField()),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
                ('slug', models.SlugField(default='', null=True)),
                ('in_stock', models.IntegerField()),
                ('info', models.TextField(null=True)),
                ('image1', models.ImageField(upload_to='FashionImages')),
                ('image2', models.ImageField(upload_to='FashionImages')),
                ('image3', models.ImageField(upload_to='FashionImages')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seller')),
            ],
            options={
                'verbose_name_plural': 'Category Fashion',
            },
        ),
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('Audio', 'Audio'), ('Cameras', 'Cameras'), ('Laptops', 'Laptops'), ('Monitors', 'Monitors'), ('Tablets', 'Tablets')], max_length=40)),
                ('price', models.BigIntegerField()),
                ('colour', models.CharField(max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(default='', null=True)),
                ('in_stock', models.IntegerField()),
                ('info', models.TextField(null=True)),
                ('image1', models.ImageField(upload_to='ElectronicImages')),
                ('image2', models.ImageField(upload_to='ElectronicImages')),
                ('image3', models.ImageField(upload_to='ElectronicImages')),
                ('seller_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.seller')),
            ],
            options={
                'verbose_name_plural': 'Category Electronics',
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='CarouselImages')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category')),
            ],
            options={
                'verbose_name_plural': 'Carousel Items',
            },
        ),
    ]
