# Generated by Django 4.0.1 on 2022-01-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashion',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='homedecor',
            name='slug',
            field=models.SlugField(default='', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='homedecor',
            name='type',
            field=models.CharField(choices=[('Clocks', 'Clocks'), ('Lights', 'Lights'), ('Paintings & Posters', 'Paintings & Posters'), ('Wall Shelves', 'Wall Shelves')], max_length=40),
        ),
    ]
